In [1]:
#basic imports
import pandas as pd
import numpy as np
import matplotlib as mpl
import json

%matplotlib inline
import warnings
import datetime as dt

# for visualizations
import matplotlib.pyplot as plt
import seaborn as sns


# for interactive visualizations
import plotly.offline as py
from plotly.offline import init_notebook_mode, iplot
import plotly.graph_objs as go
from plotly import tools
init_notebook_mode(connected = True)
import plotly.figure_factory as ff

warnings.filterwarnings("ignore")

In [7]:
file = "../datasets/empresas.csv"
import chardet
with open(file, 'rb') as rawdata:
    result = chardet.detect(rawdata.read(100000))
result

{'encoding': 'Windows-1252', 'confidence': 0.7224207175581603, 'language': ''}

In [9]:
#mydateparser = lambda x: pd.datetime.strptime(x, "%d/%m/%Y ")
df = pd.read_csv("../datasets/empresas.csv", sep=';', encoding = 'Windows-1252')
df.head()

,Nome,Email,CNPJ,Preço,Situação,Atrasado,Arquivos,Usuários,Estado,Cidade,Data de Adesão,Data de Carência,Data de Cancelamento,Armazenamento
0,W A M Serviços Contábeis Ltda,serconcontabil@uol.com.br,10.996.910/0001-20,0.0,TESTE,0,1,0,SÃ£o Paulo,Bauru,NaN,2022-04-21 15:24:18,NaN,0.0
1,gpj imobiliária,guilherme@gpjimobiliaria.com.br,44.607.426/0001-83,49.9,ATIVA,0,0,0,MG,Nova Serrana,2022-04-07 13:26:48,2022-04-21 13:24:42,NaN,0.0
2,Primor Vistorias Imobiliárias,administrativo@primorvistorias.com.br,39.621.308/0001-90,0.0,TESTE,0,1,0,Rio de Janeiro,Rio de Janeiro,NaN,2022-04-20 15:18:07,NaN,0.0
3,SGW CONSTRUCOES E ADMINISTRACOES LTDA,geovania.r@hotmail.com,44.573.162/0001-94,0.0,TESTE,0,4,0,São Paulo,Bauru,NaN,2022-04-19 10:51:04,NaN,0.0
4,FV IMÓVEIS,administrativo@imoveisfv.com,25.101.659/0001-65,49.9,ATIVA,0,2,2,Santa Catarina,Balneário Camboriú,2022-04-04 16:24:21,2022-04-18 15:56:31,NaN,0.0

In [11]:
br_estados = {
    'Acre' : 'AC',
    'Alagoas' : 'AL',
    'Amapá' : 'AP',
    'Amazonas' : 'AM',
    'Bahia' : 'BA',
    'Ceará' : 'CE',
    'Distrito Federal' : 'DF',
    'Espírito Santo' : 'ES',
    'Goiás' : 'GO',
    'Maranhão' : 'MA',
    'Mato Grosso' : 'MT',
    'Mato Grosso do Sul' : 'MS',
    'Minas Gerais' : 'MG',
    'Pará' : 'PA',
    'Paraíba' : 'PB',
    'Paraná' : 'PR',
    'Pernambuco' : 'PE',
    'Piauí' : 'PI',
    'Rio de Janeiro' : 'RJ',
    'Rio Grande do Norte' : 'RN',
    'Rio Grande do Sul' : 'RS',
    'Rondônia' : 'RO',
    'Roraima' : 'RR',
    'Santa Catarina' : 'SC',
    'São Paulo' : 'SP',
    'SÃ£o Paulo': 'SP',
    'Sergipe' : 'SE',
    'Tocantins' : 'TO'
}

df['Estado'] = df.Estado.replace(br_estados)
df

,Nome,Email,CNPJ,Preço,Situação,Atrasado,Arquivos,Usuários,Estado,Cidade,Data de Adesão,Data de Carência,Data de Cancelamento,Armazenamento
0,W A M Serviços Contábeis Ltda,serconcontabil@uol.com.br,10.996.910/0001-20,0.0,TESTE,0,1,0,SP,Bauru,NaN,2022-04-21 15:24:18,NaN,0.0
1,gpj imobiliária,guilherme@gpjimobiliaria.com.br,44.607.426/0001-83,49.9,ATIVA,0,0,0,MG,Nova Serrana,2022-04-07 13:26:48,2022-04-21 13:24:42,NaN,0.0
2,Primor Vistorias Imobiliárias,administrativo@primorvistorias.com.br,39.621.308/0001-90,0.0,TESTE,0,1,0,RJ,Rio de Janeiro,NaN,2022-04-20 15:18:07,NaN,0.0
3,SGW CONSTRUCOES E ADMINISTRACOES LTDA,geovania.r@hotmail.com,44.573.162/0001-94,0.0,TESTE,0,4,0,SP,Bauru,NaN,2022-04-19 10:51:04,NaN,0.0
4,FV IMÓVEIS,administrativo@imoveisfv.com,25.101.659/0001-65,49.9,ATIVA,0,2,2,SC,Balneário Camboriú,2022-04-04 16:24:21,2022-04-18 15:56:31,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,Paes Imóveis LTDA,contato@paesimoveis.com,02.255.145/0001-69,90.0,ATIVA,0,396,9,SC,Florianópolis,2020-09-18 17:08:14,2020-10-07 23:59:59,NaN,0.0
454,frança programação ME,tfranca2@gmail.com,16.929.335/0001-29,0.0,GRATUITO,0,30,3,SP,Campinas,2020-09-18 17:08:14,NaN,NaN,0.0
455,ADN23,contato@adn23.com.br,NaN,0.0,GRATUITO,0,12,0,SP,São Paulo,NaN,2020-02-17 23:59:59,NaN,0.0
456,Fz Imoveis LTDA,fz@fzimoveis.com.br,07.340.995/0001-89,0.0,GRATUITO,0,2,1,CE,Fortaleza,NaN,2020-04-30 23:59:59,NaN,0.0
457,Devolus Smart Solutions,contato@devolus.com,85.350.615/0001-09,59.9,INATIVA_PAG,0,48,0,CE,Fortaleza,2020-07-28 09:54:23,2020-01-31 23:59:59,2021-03-12 13:07:13,0.0

In [16]:
br_estados_ajuste = {
    'SÃƒÂ£o Paulo' : 'SP',
    'SÃƒÂ£o Paulo' : 'SP',
    'CearÃƒÂ¡' : 'CE',
    'SÃƒÂ£o Paulo' : 'SP',
    'Selecione' : 'SP',
    'ParÃƒÂƒÃ‚ÂƒÃƒÂ‚Ã‚Â¡' : 'PA',
    'SÃƒÂƒÃ‚Â£o Paulo' : 'SP',
    'SÃƒÂ£o Paulo' : 'SP', 
    'SÃƒÂ£o Paulo' : 'SP'
}

df['Estado'] = df.Estado.replace(br_estados_ajuste)
df

,Nome,Email,CNPJ,Preço,Situação,Atrasado,Arquivos,Usuários,Estado,Cidade,Data de Adesão,Data de Carência,Data de Cancelamento,Armazenamento
0,W A M Serviços Contábeis Ltda,serconcontabil@uol.com.br,10.996.910/0001-20,0.0,TESTE,0,1,0,SP,Bauru,NaN,2022-04-21 15:24:18,NaN,0.0
1,gpj imobiliária,guilherme@gpjimobiliaria.com.br,44.607.426/0001-83,49.9,ATIVA,0,0,0,MG,Nova Serrana,2022-04-07 13:26:48,2022-04-21 13:24:42,NaN,0.0
2,Primor Vistorias Imobiliárias,administrativo@primorvistorias.com.br,39.621.308/0001-90,0.0,TESTE,0,1,0,RJ,Rio de Janeiro,NaN,2022-04-20 15:18:07,NaN,0.0
3,SGW CONSTRUCOES E ADMINISTRACOES LTDA,geovania.r@hotmail.com,44.573.162/0001-94,0.0,TESTE,0,4,0,SP,Bauru,NaN,2022-04-19 10:51:04,NaN,0.0
4,FV IMÓVEIS,administrativo@imoveisfv.com,25.101.659/0001-65,49.9,ATIVA,0,2,2,SC,Balneário Camboriú,2022-04-04 16:24:21,2022-04-18 15:56:31,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,Paes Imóveis LTDA,contato@paesimoveis.com,02.255.145/0001-69,90.0,ATIVA,0,396,9,SC,Florianópolis,2020-09-18 17:08:14,2020-10-07 23:59:59,NaN,0.0
454,frança programação ME,tfranca2@gmail.com,16.929.335/0001-29,0.0,GRATUITO,0,30,3,SP,Campinas,2020-09-18 17:08:14,NaN,NaN,0.0
455,ADN23,contato@adn23.com.br,NaN,0.0,GRATUITO,0,12,0,SP,São Paulo,NaN,2020-02-17 23:59:59,NaN,0.0
456,Fz Imoveis LTDA,fz@fzimoveis.com.br,07.340.995/0001-89,0.0,GRATUITO,0,2,1,CE,Fortaleza,NaN,2020-04-30 23:59:59,NaN,0.0
457,Devolus Smart Solutions,contato@devolus.com,85.350.615/0001-09,59.9,INATIVA_PAG,0,48,0,CE,Fortaleza,2020-07-28 09:54:23,2020-01-31 23:59:59,2021-03-12 13:07:13,0.0

In [17]:
#verificando se tem estados ainda errados
print(df[df['Estado'].str.len() > 2.0])

Empty DataFrame
Columns: [Nome, Email, CNPJ, Preço, Situação, Atrasado, Arquivos, Usuários, Estado, Cidade, Data de Adesão, Data de Carência, Data de Cancelamento, Armazenamento]
Index: []

In [20]:
df['Data de Adesão'] = pd.to_datetime(df['Data de Adesão'], format='%Y-%m-%d %H:%M:%S')
df['Data de Carência'] = pd.to_datetime(df['Data de Carência'], format='%Y-%m-%d %H:%M:%S')
df['Data de Cancelamento'] = pd.to_datetime(df['Data de Cancelamento'], format='%Y-%m-%d %H:%M:%S')
df.head()

,Nome,Email,CNPJ,Preço,Situação,Atrasado,Arquivos,Usuários,Estado,Cidade,Data de Adesão,Data de Carência,Data de Cancelamento,Armazenamento
0,W A M Serviços Contábeis Ltda,serconcontabil@uol.com.br,10.996.910/0001-20,0.0,TESTE,0,1,0,SP,Bauru,NaT,2022-04-21 15:24:18,NaT,0.0
1,gpj imobiliária,guilherme@gpjimobiliaria.com.br,44.607.426/0001-83,49.9,ATIVA,0,0,0,MG,Nova Serrana,2022-04-07 13:26:48,2022-04-21 13:24:42,NaT,0.0
2,Primor Vistorias Imobiliárias,administrativo@primorvistorias.com.br,39.621.308/0001-90,0.0,TESTE,0,1,0,RJ,Rio de Janeiro,NaT,2022-04-20 15:18:07,NaT,0.0
3,SGW CONSTRUCOES E ADMINISTRACOES LTDA,geovania.r@hotmail.com,44.573.162/0001-94,0.0,TESTE,0,4,0,SP,Bauru,NaT,2022-04-19 10:51:04,NaT,0.0
4,FV IMÓVEIS,administrativo@imoveisfv.com,25.101.659/0001-65,49.9,ATIVA,0,2,2,SC,Balneário Camboriú,2022-04-04 16:24:21,2022-04-18 15:56:31,NaT,0.0

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Nome                  457 non-null    object
 1   Email                 456 non-null    object
 2   CNPJ                  434 non-null    object
 3   Preço                 448 non-null    float64
 4   Situação              448 non-null    object
 5   Atrasado              458 non-null    int64
 6   Arquivos              458 non-null    int64
 7   Usuários              458 non-null    int64
 8   Estado                259 non-null    object
 9   Cidade                258 non-null    object
 10  Data de Adesão        143 non-null    datetime64[ns]
 11  Data de Carência      407 non-null    datetime64[ns]
 12  Data de Cancelamento  63 non-null     datetime64[ns]
 13  Armazenamento         458 non-null    float64
dtypes: datetime64[ns](3), float64(2), int64(3), object(6)
memory usage: 50.2+ KB

In [22]:
# colunas = {"Nome":"nome","Email":"email","Telefone":"telefone","CPF/CNPJ":"CPF/CNPJ","Data cadastro":"dtcadastro","Cidade":"cidade","UF":"uf","Qtd vistoria":"qtdvistoria","Qtd foto":"qtdfoto","Armazenamento":"armazenamento",
#            "Data limite teste":"limiteteste","Vencimento":"vencimento","Valor":"valor",
#            "Desconto":"desconto","Valor vistoria adicional":"vistoriaadd","Data compra":"dtcompra","Data cancelamento":"dtcancelamento","Data cancelamento":"dtcancelamento","Situação":"situacao"}
# df.rename(columns=colunas, inplace=True)
# df.head()

In [23]:
df.to_csv("../datasets/df_empresas_fast4sign_geral.csv")

In [26]:
df_empresas = pd.read_csv('../datasets/df_empresas_fast4sign_geral.csv')
df_empresas

,Unnamed: 0,Nome,Email,CNPJ,Preço,Situação,Atrasado,Arquivos,Usuários,Estado,Cidade,Data de Adesão,Data de Carência,Data de Cancelamento,Armazenamento
0,0,W A M Serviços Contábeis Ltda,serconcontabil@uol.com.br,10.996.910/0001-20,0.0,TESTE,0,1,0,SP,Bauru,NaN,2022-04-21 15:24:18,NaN,0.0
1,1,gpj imobiliária,guilherme@gpjimobiliaria.com.br,44.607.426/0001-83,49.9,ATIVA,0,0,0,MG,Nova Serrana,2022-04-07 13:26:48,2022-04-21 13:24:42,NaN,0.0
2,2,Primor Vistorias Imobiliárias,administrativo@primorvistorias.com.br,39.621.308/0001-90,0.0,TESTE,0,1,0,RJ,Rio de Janeiro,NaN,2022-04-20 15:18:07,NaN,0.0
3,3,SGW CONSTRUCOES E ADMINISTRACOES LTDA,geovania.r@hotmail.com,44.573.162/0001-94,0.0,TESTE,0,4,0,SP,Bauru,NaN,2022-04-19 10:51:04,NaN,0.0
4,4,FV IMÓVEIS,administrativo@imoveisfv.com,25.101.659/0001-65,49.9,ATIVA,0,2,2,SC,Balneário Camboriú,2022-04-04 16:24:21,2022-04-18 15:56:31,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,453,Paes Imóveis LTDA,contato@paesimoveis.com,02.255.145/0001-69,90.0,ATIVA,0,396,9,SC,Florianópolis,2020-09-18 17:08:14,2020-10-07 23:59:59,NaN,0.0
454,454,frança programação ME,tfranca2@gmail.com,16.929.335/0001-29,0.0,GRATUITO,0,30,3,SP,Campinas,2020-09-18 17:08:14,NaN,NaN,0.0
455,455,ADN23,contato@adn23.com.br,NaN,0.0,GRATUITO,0,12,0,SP,São Paulo,NaN,2020-02-17 23:59:59,NaN,0.0
456,456,Fz Imoveis LTDA,fz@fzimoveis.com.br,07.340.995/0001-89,0.0,GRATUITO,0,2,1,CE,Fortaleza,NaN,2020-04-30 23:59:59,NaN,0.0
457,457,Devolus Smart Solutions,contato@devolus.com,85.350.615/0001-09,59.9,INATIVA_PAG,0,48,0,CE,Fortaleza,2020-07-28 09:54:23,2020-01-31 23:59:59,2021-03-12 13:07:13,0.0

In [27]:
df['Preço'].sum()

20169.7

In [30]:
result = df[df['Situação'] == 'ATIVA']
mrr = result['Preço'].sum()
mrr

15740.399999999998

In [36]:
result.size

1274

In [38]:
result.shape[0]

91

In [40]:
result = df[df['Situação'] == 'ATIVA']
ativos = result.shape[0]
ativos

91

In [45]:
len(result.index)

91

# Preparando aquivo Empresas Usando agrupado por UF

In [49]:
df_uf = df[(df['Situação'] == 'ATIVA') | (df['Situação'] == 'GRATUITO')]
df_uf

,Nome,Email,CNPJ,Preço,Situação,Atrasado,Arquivos,Usuários,Estado,Cidade,Data de Adesão,Data de Carência,Data de Cancelamento,Armazenamento
1,gpj imobiliária,guilherme@gpjimobiliaria.com.br,44.607.426/0001-83,49.90,ATIVA,0,0,0,MG,Nova Serrana,2022-04-07 13:26:48,2022-04-21 13:24:42,NaT,0.0
4,FV IMÓVEIS,administrativo@imoveisfv.com,25.101.659/0001-65,49.90,ATIVA,0,2,2,SC,Balneário Camboriú,2022-04-04 16:24:21,2022-04-18 15:56:31,NaT,0.0
6,Alex Alexandre Quadros Fiuza,evorapk@gmail.com,593.708.230-34,79.90,ATIVA,0,0,0,NaN,NaN,2022-03-30 15:19:13,2022-04-14 19:30:14,NaT,0.0
11,Phanebecker & Ferreira Ltda.,pousadaalecrim@gmail.com,11.226.906/0001-45,0.00,GRATUITO,0,0,0,NaN,NaN,NaT,2022-04-11 09:33:27,NaT,0.0
12,Block Imóveis Ltda,wallace@blockimoveis.com.br,26.475.689/0001-02,71.91,ATIVA,0,3,0,RJ,Rio de Janeiro,2022-04-01 15:14:42,2022-04-15 12:06:23,NaT,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,Acapulco Empreendimentos Imobiliários American...,ester@acapulcoimoveis.com.br,52.150.448/0001-95,0.00,GRATUITO,0,0,0,SP,Americana,NaT,2020-02-26 23:59:59,NaT,0.0
453,Paes Imóveis LTDA,contato@paesimoveis.com,02.255.145/0001-69,90.00,ATIVA,0,396,9,SC,Florianópolis,2020-09-18 17:08:14,2020-10-07 23:59:59,NaT,0.0
454,frança programação ME,tfranca2@gmail.com,16.929.335/0001-29,0.00,GRATUITO,0,30,3,SP,Campinas,2020-09-18 17:08:14,NaT,NaT,0.0
455,ADN23,contato@adn23.com.br,NaN,0.00,GRATUITO,0,12,0,SP,São Paulo,NaT,2020-02-17 23:59:59,NaT,0.0
456,Fz Imoveis LTDA,fz@fzimoveis.com.br,07.340.995/0001-89,0.00,GRATUITO,0,2,1,CE,Fortaleza,NaT,2020-04-30 23:59:59,NaT,0.0

In [50]:
df_uf = df_uf[['Estado','Preço']]
df_uf

    Estado  Preço
1       MG  49.90
4       SC  49.90
6      NaN  79.90
11     NaN   0.00
12      RJ  71.91
..     ...    ...
452     SP   0.00
453     SC  90.00
454     SP   0.00
455     SP   0.00
456     CE   0.00

[373 rows x 2 columns]

In [51]:
df_uf_gr = (df_uf.groupby(['Estado'])['Preço'].agg(['sum']).sort_values(by='sum', ascending=False).reset_index())
df_uf_gr

   Estado      sum
0      SP  8675.20
1      MG  2531.60
2      RS  2019.79
3      SC   739.10
4      RJ   551.41
5      MS   289.60
6      MT   174.80
7      DF   159.90
8      BA   109.80
9      PA    79.90
10     CE    59.90
11     PE    59.90
12     MA    49.90
13     AM    49.90
14     SE     0.00
15     AL     0.00
16     RN     0.00
17     PR     0.00
18     PI     0.00
19     ES     0.00
20     TO     0.00